# ─── JWT (partagé avec le service IAM) ───────────────────────────────────────
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 3600000

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
  packages-to-scan: tn.iteam.hrprojectbackend.users.controller,tn.iteam.hrprojectbackend.leave.controller,tn.iteam.hrprojectbackend.dashboard.controller,tn.iteam.hrprojectbackend.chat.controller
  paths-to-match: /api/**
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

spring:
  ai:
    vertex:
      ai:
        gemini:
          project-id: gen-lang-client-0640135018
          location: us-central1
          chat:
            options:
              model: gemini-2.0-flash
              temperature: 0.2

    mcp:
      server:
        enabled: false
      client:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_db
    username: hr_user
    password: hr_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: hr-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
